import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>atti</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <div>
        <h1>Welcome to atti</h1>
      </div>
    </>
  );
}
